### ISSUE TITLE
Concernant l'emplacement des durées/Time location 

### ISSUE THREAD

**Issue by whoamitty** [TeddyBoomer/grapheMPM#10]
### In french
Bonjour, est il possible de mettre les numéros/niveaux
au dessus des sommets/repères
et pas en dessous comme c'est présenté sur le readme ?

### Translate in english
Hello, is it possible to put the numbers / levels
above the vertices / marks
and not below as it is presented on the readme ?

![Graph presented in the readme](https://raw.githubusercontent.com/TeddyBoomer/grapheMPM/master/illustrations/ex-ed-nomarge.png)

**Comment by TeddyBoomer** [comment]
Bonjour, je ne comprends pas trop la question: 
les niveaux sont gérés par l'option `show_level=True` et cela apparait au dessus des colonnes de sommets.
Pouvez-vous préciser svp?
cordialement,

**Comment by whoamitty** [comment]
> Bonjour, je ne comprends pas trop la question: 
> les niveaux sont gérés par l'option `show_level=True` et cela apparait au dessus des colonnes de sommets.
> Pouvez-vous préciser svp?
> cordialement,

Bonjour, je me suis trompé, je voulais dire le nombre de jours, pas les niveaux.

J'ai mis un exemple en image ci-dessous.
ça seras plus parlant je pense

Bien cordialement.


![IMG_20230916_102112.jpg](https://github.com/TeddyBoomer/grapheMPM/assets/74999206/48606e64-3ece-4f1d-a5ce-3ad5118d46dd)

**Comment by TeddyBoomer** [comment]
Bonjour, je suis en train d'ajouter une option `presentation=3` possible, avec ce que vous proposez. Dans ce cas les dates et les marges apparaîtront au dessus en carré. Patience…

**Comment by TeddyBoomer** [comment]
Bonsoir, je viens de publier une version v0.7.2 pour tenir compte de votre demande:
avec `presentation=3` les dates se placeront au dessus du nom de nœud.
Cordialement

**Comment by whoamitty** [comment]
Bonsoirs, c'est ma première issues avec
une réponse.

Merci beaucoup d'avoir pris en compte ma demande.

Cordialement
