### ISSUE TITLE
Tâches **immédiatement** antérieures

### ISSUE THREAD

**Issue by iCodePup** [TeddyBoomer/grapheMPM#11]
Bonjour,

Existe-il une fonction pour calculer les tâches **immédiatement** antérieures si on donne l'ensemble des prédécesseurs pour chaque tâche :

 Par exemple :
```
# dico de l'ensemble des prédécesseurs
p = {"A": "", "B": "", "C": "AB", "D": "AB", "E":"B",
     "F":"A", "G": "A", "H":"AF", "I":"AF", "J": "ABEFGHI", "K": "ABD","L":"ABDK","M":"ABD","N":"ABCDEFGHIJKLM"} 
```

donne les taches **immédiatement** antérieures suivantes :
```

p = {"A": "", "B": "", "C": "AB", "D": "AB", "E":"B",
     "F":"A", "G": "A", "H":"F", "I":"F", "J": "EGHI", "K": "D","L":"K","M":"D","N":"CJLM"} 
```

Merci d'avance.

**Comment by TeddyBoomer** [comment]
Bonjour, je ne comprends ce qui est "immédiatement" antérieur:
Le dictionnaire des prédecesseurs, ou son alter-ego des successeurs, indique déjà des arcs orientés directs d'un point vers un autre. Dans votre exemple, de A à H, il y a  un arc direct. Pourquoi H n'aurait que F directement antérieur?

**Comment by iCodePup** [comment]
Bonjour,
Merci pour votre intérêt.
Pour H on a les sommets AF comme prédécesseurs .
Or si on analyse le sommet F on se rend compte qu'il a également le sommet A comme prédécesseur.
Par conséquent, après simplification , on doit ne garder que la tâche H a comme prédécesseur la tâche F ( car comme F possède deja la tâche A comme prédécesseur elle est donc redondante, inutile et de surcroit surcharge le graphe avec des arcs inutiles).

La détermination des tâches immédiatement antérieures est la première étape importante, puis calcul des niveaux et enfin le dessin du graphe.

**Comment by TeddyBoomer** [comment]
Bonjour, il est possible de programmer une fonction pour créer le dictionnaire des "antécédents immédiats", toutefois, elle n'est pas liée à l'algorithme des graphes MPM, c'est une commodité à votre discrétion:

un antécédent est immédiat ssi il n'a pas de successeurs dans la fermeture transitive parmi les autres antécédents.
On peut programmer la fonction de la manière suivante: 

```python
from grapheMPM import GrapheSimple

p = {"A": "", "B": "", "C": "AB", "D": "AB", "E":"B",
     "F":"A", "G": "A", "H":"AF", "I":"AF", "J": "ABEFGHI", "K": "ABD","L":"ABDK","M":"ABD","N":"ABCDEFGHIJKLM"}
G = GrapheSimple(pred=p)

def immediat(g):
    """renvoie le dict des antécédents immédiats d'un GrapheSimple g"""
    out = {}
    N = g.mat_adj.shape[0]
    for j in range(1, N+1): # sommets par numéro
        out[g.num_sommets[j]] = []
        predsj = []
        for i in range(1, N+1):
            if g.mat_adj[i-1,j-1] == 1:
                predsj.append(i)
        for k in predsj:
            I = [G.mat_ferm_transitive[k-1, m-1] for m in predsj]
            is_immediat = 1 not in I
            if is_immediat:
                out[g.num_sommets[j]].append(g.num_sommets[k])
        out[g.num_sommets[j]] = "".join(out[g.num_sommets[j]])
    return out

print(immediat(G))
```

La sortie est bien ce que vous souhaitez:
` {'A': '', 'B': '', 'C': 'AB', 'D': 'AB', 'E': 'B', 'F': 'A', 'G': 'A', 'H': 'F', 'I': 'F', 'J': 'EGHI', 'K': 'D', 'L': 'K', 'M': 'D', 'N': 'CJLM'}`

Il faut garder cette petite fonction avec vous pour dépanner…
je clôture le ticket, bien cordialement,
