### ISSUE TITLE
Calcul des dates et marges en flottant

### ISSUE THREAD

**Issue by cpierquet** [TeddyBoomer/grapheMPM#2]
Serait-il possible de faire les calculs avec des flottants (peut-être avec un choix par défaut pour les entiers, et une option pour autoriser les flottants) ? 
Certes il se pourrait qu'il y ait des dates affichées en 4.0 par contre...

**Comment by TeddyBoomer** [comment]
Bonjour, oui c'est possible, mais c'est un peu pénible:
par nature les flottants sont pénibles.
et on touche à une partie dirty dans le code.

Je pense avoir un ajustement satisfaisant pour traiter les pondérations flottantes; je publie ça cet après-midi…(30/11)

**Comment by cpierquet** [comment]
Merci ;-)

**Comment by TeddyBoomer** [comment]
C'est corrigé en v0.4, tu peux tester.
cdlt
