### ISSUE TITLE
Affichage des niveaux - Choix du format de sortie 

### ISSUE THREAD

**Issue by xansiaux** [TeddyBoomer/grapheMPM#3]
Bonjour,
serait-il possible d'avoir **l'affichage des niveaux sur le graphe**, et de choisir le **format de sortie** ( .png, .ps, etc.)?

**Cerise sur le gâteau:** 
je voudrais ne pas avoir à entrer le nom du fichier image, mais que ce soit le nom du fichier python qui soit choisi comme nom du fichier image par défaut
( exemple de code pour afficher le nom du fichier( mais je suis sûr que tu connais déjà ;=))  : 
```python
    import __main__ as main
    print(main.__file__[:-3])
``` 
)
Est-ce possible ?

Encore **un grand merci** pour le travail accompli. 

Xavier.

**Comment by TeddyBoomer** [comment]
Bonsoir Xavier, et merci pour ton message.
pour les niveaux: il faut que je me plonge dans la documentation de graphviz; c'est peut-être possible, mais pas dans l'immédiat car les conseils de classe et remises de bulletins vont m'accaparer.

Pour le format de sortie: dans ton script python tu rajoutes:
`G.gv.format="ps"`ou png ou pdf etc.
avant d'executer G.gv.render("sortie").

Pour le nom de fichier: non je ne connaissais pas; j'ai déjà codé un module avec un __main__ mais sans réelle maîtrise du sujet. À mon avis il faut toi même bricoler ton code après import de graphMPM;
Actuellement je l'utilise pour générer plusieurs graphes d'exos à la suite, donc je n'ai pas l'utilité d'un seul nom de fichier identique à celui du script.
Bon week end!

**Comment by xansiaux** [comment]
Bonjour,
Boris,
effectivement, tout ce que tu me dis fonctionne bien :
```python
from grapheMPM import GrapheMPM

import __main__ as main

# dico des prédecesseurs
p = {"Début":"","A": ['Début'],"B" : "D", "C": "HFE", "D": "A", "E": "K","F":"L", "G": "I", "H":"L", "I":"C", "J":"B","K":"J","L":"K","M":"K","N":"G", "Fin": "MN"}
# dico des pondérations
w = {"Début": 0, "Fin": 0,"A": 10, "B": 4, "C": 2, "D": 5, "E": 4,"F": 3, "G": 3, "H": 6, "I": 5, "J": 9, "K": 5, "L": 8, "M": 5, "N": 2}
G = GrapheMPM(pred=p, pond=w,presentation=2)
G.setlevel()
G.earliestdate()
G.latestdate()
G.makeGraphviz()
G.gv.render(main.__file__[:-3])
G.gv.format="eps"
G.gv.render(main.__file__[:-3])
```
J'obtiens bien un fichier qui porte le nom de mon script python en version .png ( pour internet ) et eps (pour LaTeX).

Je m'explique sur cette demande:
Dans mon éditeur  ( notepad++) , je compile du LaTeX.
Pour insérer un graphe, j'ai mis un raccourci ( F2) qui lance un script batch qui:

- créée un fichier python appelé "fichier_i.py" où i est le numéro du fichier.
- colle le contenu du presse-papier dans ce fichier "fichier_i.py" 
- l'ouvre dans notepad++
- insère dans le presse papier l'instruction LaTeX qui insère le résultat du  fichier "fichier_i.py" dans mon document LaTeX final

Je copie donc le code Python dans le presse-papier, je lance F2, je colle l'instruction LaTeX; il ne me reste plus alors qu'à modifier le code Python, à le faire fonctionner, et c'est fini.

Je connais beaucoup moins que toi Python, aussi ton script me dépanne énormément.

Bons conseils de classe, 
A bientôt,
Encore merci,
Xavier.
