### ISSUE TITLE
Durée du projet sur l'étiquette de fin

### ISSUE THREAD

**Issue by xansiaux** [TeddyBoomer/grapheMPM#5]
Bonjour,
et encore merci pour ton travail.
Je me pose une question: 
pourquoi as-tu retiré la durée totale qu'on pouvait lire auparavant sous le sommet "fin"?
Y-a-t-il une raison?
Bien cordialement,
Xavier .

**Comment by TeddyBoomer** [comment]
Bonjour, ce n'est pas vraiment volontaire:
dans cette version, les sommets début et fin sont rajoutés hors de l'algorithme de calcul et prennent juste une forme de bulle; ce qui évite de les définir à l'initialisation.
En y réfléchissant maintenant, c'est probablement incorrect car s'il y a deux tâches finales, il faut bien reporter un total calculé dans le sommet fin…et en plus la durée de J dans l'exemple n'est plus utilisée.
bref je vais y réfléchir cet été pour corriger ça.
merci pour le retour, bon week end!

**Comment by TeddyBoomer** [comment]
Bonjour, je viens de publier un correctif→ on passe en v0.5.1
peux-tu essayer, ça devrait être ok.
en ajoutant -U ou --upgrade dans la commande pip, ça devrait directement désinstaller l'ancienne version pour passer à la nouvelle.
**À noter**: plus besoin d'appeler la méthode setlevel car elle est utilisée dès l'initialisation pour calculer les niveaux et rajouter le nœud final.
