### ISSUE TITLE
Petit souci

### ISSUE THREAD

**Issue by xansiaux** [TeddyBoomer/grapheMPM#6]
Bonjour,
Boris,
 encore un grand merci pour ton travail!
J'ai juste un petit souci avec ce code:

```python3
from grapheMPM import GrapheMPM

import __main__ as main

# dico des prédecesseurs
p = {"a": "","b" : "", "c": "", "d": "a", "e": "ab","f":"b", "g": "ef", "h":"cf"}
# dico des pondérations
w = {"a": 26, "b": 25, "c": 40, "d": 17, "e": 8,"f": 14, "g": 4, "h": 4}
G = GrapheMPM(pred=p, pond=w,presentation=2,show_level=True)
G.earliestdate()
G.latestdate()
G.makeGraphviz()
G.gv.render(main.__file__[:-3])
G.gv.format="eps"
G.gv.render(main.__file__[:-3])
```
J'obtiens ceci :
![graphe_exo_9](https://user-images.githubusercontent.com/16732402/94403894-6526bd00-016e-11eb-8473-64364cc777a6.png)
alors que je devrais obtenir cela :
![Image 086](https://user-images.githubusercontent.com/16732402/94404005-94d5c500-016e-11eb-8a1c-f3f4cb8044df.png)

Encore merci, et bon courage pour la suite,
Amitiés,
Xavier.

**Comment by xansiaux** [comment]
Par contre, si j'ajoute un sommet "Fin", cela fonctionne bien , comme avant.
![graphe_exo_9](https://user-images.githubusercontent.com/16732402/94478338-6fc76d80-01d3-11eb-85d0-564b8252d48a.png)

**Comment by TeddyBoomer** [comment]
Bonjour Xavier, et merci pour ce retour: voilà une nouvelle situation qui n'est pas correctement gérée.
dans mon code, seuls les sommets de dernier niveau sont automatiquement reliés à la fin.
Visiblement, là il faut que je modifie en :*relier à la fin, tous les sommets sans successeurs*
… j'essaierai de corriger ça bientôt (au pire vers les vacances de Toussaint)

à suivre…

**Comment by TeddyBoomer** [comment]
Bon le correctif a l'air de marcher: (j'ai aussi désactivé le niveau "last")
![correctif](https://user-images.githubusercontent.com/760950/95621705-6dd29980-0a72-11eb-9642-b4b86e43ce4d.png)
v0.5.4 d'ici peu.

**Comment by TeddyBoomer** [comment]
Correctif publié v0.5.4;
merci à toi, bon week end!
