### ISSUE TITLE
Récupérer prédécesseurs

### ISSUE THREAD

**Issue by xansiaux** [TeddyBoomer/grapheMPM#7]
Bonjour, 
Boris,
je ne sais pas si c'est le bon endroit où poster cela:
j'ai un graphe simple que j'ai défini avec le dictionnaire des successeurs.
Je souhaiterais récupérer le dictionnaire des prédécesseurs.
Puis-je y accéder? ( j'ai l'impression que non pour l'instant)
exemple:
```python3
s = {"A": "BD","B" : "C", "C": "BD", "D": "D", "E": "AC"}
G = GrapheSimple(succ = s)
print(G.pred) #prédécesseurs
```
Merci beaucoup,
Xavier.

**Comment by TeddyBoomer** [comment]
Bonsoir Xavier,
oui oui c'est possible, c'est parce que la variable nommée en entrée ne correspond pas à l'attribut de l'objet:
il faut faire

`G.predecesseurs, G.successeurs`

pour accéder à ces deux dictionnaires;
pour fouiner dans les attributs de l'objet, tu peux taper `dir(G)`
Cordialement,
