### ISSUE TITLE
Forcer les coordonnées d'un sommet

### ISSUE THREAD

**Issue by xansiaux** [TeddyBoomer/grapheMPM#8]
Bonjour,
Boris,
je m'interroge sur ta phrase:
![image](https://user-images.githubusercontent.com/16732402/112504843-79015380-8d8c-11eb-9ded-5067319d8d18.png)
Est-il possible de fixer les coordonnées d'un sommet?
Graphviz le permet-il avec Digraph?
Bonne continuation,
Bien cordialement,
Xavier.

**Comment by TeddyBoomer** [comment]
Bonjour Xavier, 
je ne pense pas qu'on puisse fixer les coordonnées de sommets sans s'embarquer dans  un recalcul complet et pénible: graphviz est conçu pour gérer ça à notre place.
on définit surtout des zones de sous-graphe pour organiser (pour mpm, on regroupe par niveau).
on définit aussi l'orientation globale du graphe (gauche vers droite, ou haut vers bas par exemple)
Tu peux éventuellement jeter un œil sur les [attributs des nœuds](https://graphviz.org/doc/info/attrs.html) disponibles dans graphviz: 
il y a un attribut "pos" mais je serais bien en peine de l'utiliser.

Pour l'objet GrapheMPM, j'ai forcé les regroupements par niveau dans des sous-graphes invisibles qui conviennent; pour GrapheSimple je ne l'ai pas fait, c'est comme ça que je me suis rendu compte que graphviz ne le fait pas d'office.

Bien cordialement,
Boris

**Comment by xansiaux** [comment]
Merci pour ta réponse,
Boris,
je comprends mieux ce que tu voulais dire par "forcer".
Effectivement, j'ai l'impression que "pos" ne sert qu'avec le "visualisateur" neato ( d'après ce que j'ai cru comprendre).
A plus, 
encore merci,
Xavier.
