### ISSUE TITLE
Décalage des niveaux

### ISSUE THREAD

**Issue by xansiaux** [TeddyBoomer/grapheMPM#9]
Bonjour Boris, et merci pour cette version.
Petit bug cependant : 
lors de l'affichage des niveaux d'un graphe MPM, le début est considéré comme un sommet, et Les niveaux sont donc décalés de 1.
Encore une fois, merci pour ton formidable travail.
Bien cordialement,
Xavier.

**Comment by TeddyBoomer** [comment]
Bonjour Xavier, merci pour le signalement; j'essaie de m'en occuper ces jours-ci… mais c'est pas gagné!
cordialement, et meilleurs vœux pour 2023!

**Comment by TeddyBoomer** [comment]
Bonjour Xavier, je teste un correctif: 
je pense (enfin) avoir compris l'écriture des attributs rank="same" et autres pour DOT;
Je vais probablement réactiver la construction par "clusters": le seul bémol est que les titres "niveaux" peuvent être surpassés par des arcs. 
Autrement ça rend pas mal; c'est un contournant vilain qui a provoqué le bug d'affichage: avec les clusters j'avais les titres aux bons endroits (sauf qu'il faut enlever le niveau de "fin" en fait)
à suivre rapidement,
bien cordialement

**Comment by TeddyBoomer** [comment]
Bonjour Xavier,
correctif publié à l'instant avec quelques autres nettoyages (si on update numpy et pandas, on obtenait des "DeprecationWarning")
le code est plus propre grâce à ton signalement!
